// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace rat_game_api.Migrations
{
    [DbContext(typeof(RatGameContext))]
    [Migration("20241121030412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RatGameApi.Domain.HighScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HighScores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = 1,
                            Score = 52
                        },
                        new
                        {
                            Id = 2,
                            Difficulty = 2,
                            Score = 29
                        });
                });

            modelBuilder.Entity("RatGameApi.Domain.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Item1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = 1,
                            Item1 = "cottage",
                            Item2 = "swiss",
                            Item3 = "cake",
                            Solution = "cheese"
                        },
                        new
                        {
                            Id = 2,
                            Difficulty = 1,
                            Item1 = "cream",
                            Item2 = "skate",
                            Item3 = "water",
                            Solution = "ice"
                        },
                        new
                        {
                            Id = 3,
                            Difficulty = 1,
                            Item1 = "loser",
                            Item2 = "throat",
                            Item3 = "spot",
                            Solution = "sore"
                        },
                        new
                        {
                            Id = 4,
                            Difficulty = 1,
                            Item1 = "show",
                            Item2 = "life",
                            Item3 = "row",
                            Solution = "boat"
                        },
                        new
                        {
                            Id = 5,
                            Difficulty = 1,
                            Item1 = "night",
                            Item2 = "wrist",
                            Item3 = "stop",
                            Solution = "watch"
                        },
                        new
                        {
                            Id = 6,
                            Difficulty = 1,
                            Item1 = "duck",
                            Item2 = "fold",
                            Item3 = "dollar",
                            Solution = "bill"
                        },
                        new
                        {
                            Id = 7,
                            Difficulty = 1,
                            Item1 = "rocking",
                            Item2 = "wheel",
                            Item3 = "high",
                            Solution = "chair"
                        },
                        new
                        {
                            Id = 8,
                            Difficulty = 1,
                            Item1 = "dew",
                            Item2 = "comb",
                            Item3 = "bee",
                            Solution = "honey"
                        },
                        new
                        {
                            Id = 9,
                            Difficulty = 1,
                            Item1 = "fountain",
                            Item2 = "baking",
                            Item3 = "pop",
                            Solution = "soda"
                        },
                        new
                        {
                            Id = 10,
                            Difficulty = 1,
                            Item1 = "preserve",
                            Item2 = "ranger",
                            Item3 = "tropical",
                            Solution = "forest"
                        },
                        new
                        {
                            Id = 11,
                            Difficulty = 2,
                            Item1 = "aid",
                            Item2 = "rubber",
                            Item3 = "wagon",
                            Solution = "band"
                        },
                        new
                        {
                            Id = 12,
                            Difficulty = 2,
                            Item1 = "flake",
                            Item2 = "mobile",
                            Item3 = "cone",
                            Solution = "snow"
                        },
                        new
                        {
                            Id = 13,
                            Difficulty = 1,
                            Item1 = "cracker",
                            Item2 = "fly",
                            Item3 = "fighter",
                            Solution = "fire"
                        },
                        new
                        {
                            Id = 14,
                            Difficulty = 2,
                            Item1 = "safety",
                            Item2 = "cushion",
                            Item3 = "point",
                            Solution = "pin"
                        },
                        new
                        {
                            Id = 15,
                            Difficulty = 1,
                            Item1 = "cane",
                            Item2 = "daddy",
                            Item3 = "plum",
                            Solution = "sugar"
                        },
                        new
                        {
                            Id = 16,
                            Difficulty = 2,
                            Item1 = "dream",
                            Item2 = "break",
                            Item3 = "light",
                            Solution = "day"
                        },
                        new
                        {
                            Id = 17,
                            Difficulty = 2,
                            Item1 = "fish",
                            Item2 = "mine",
                            Item3 = "rush",
                            Solution = "gold"
                        },
                        new
                        {
                            Id = 18,
                            Difficulty = 1,
                            Item1 = "political",
                            Item2 = "surprise",
                            Item3 = "line",
                            Solution = "party"
                        },
                        new
                        {
                            Id = 19,
                            Difficulty = 1,
                            Item1 = "measure",
                            Item2 = "worm",
                            Item3 = "video",
                            Solution = "tape"
                        },
                        new
                        {
                            Id = 20,
                            Difficulty = 2,
                            Item1 = "high",
                            Item2 = "district",
                            Item3 = "house",
                            Solution = "school/court"
                        },
                        new
                        {
                            Id = 21,
                            Difficulty = 3,
                            Item1 = "sense",
                            Item2 = "courtesy",
                            Item3 = "place",
                            Solution = "common"
                        },
                        new
                        {
                            Id = 22,
                            Difficulty = 1,
                            Item1 = "worm",
                            Item2 = "shelf",
                            Item3 = "end",
                            Solution = "book"
                        },
                        new
                        {
                            Id = 23,
                            Difficulty = 4,
                            Item1 = "piece",
                            Item2 = "mind",
                            Item3 = "dating",
                            Solution = "game"
                        },
                        new
                        {
                            Id = 24,
                            Difficulty = 3,
                            Item1 = "flower",
                            Item2 = "friend",
                            Item3 = "scout",
                            Solution = "girl"
                        },
                        new
                        {
                            Id = 25,
                            Difficulty = 2,
                            Item1 = "river",
                            Item2 = "note",
                            Item3 = "account",
                            Solution = "bank"
                        },
                        new
                        {
                            Id = 26,
                            Difficulty = 2,
                            Item1 = "print",
                            Item2 = "berry",
                            Item3 = "bird",
                            Solution = "blue"
                        },
                        new
                        {
                            Id = 27,
                            Difficulty = 3,
                            Item1 = "pie",
                            Item2 = "luck",
                            Item3 = "belly",
                            Solution = "pot"
                        },
                        new
                        {
                            Id = 28,
                            Difficulty = 1,
                            Item1 = "date",
                            Item2 = "alley",
                            Item3 = "fold",
                            Solution = "blind"
                        },
                        new
                        {
                            Id = 29,
                            Difficulty = 3,
                            Item1 = "opera",
                            Item2 = "hand",
                            Item3 = "dish",
                            Solution = "soap"
                        },
                        new
                        {
                            Id = 30,
                            Difficulty = 2,
                            Item1 = "cadet",
                            Item2 = "capsule",
                            Item3 = "ship",
                            Solution = "space"
                        },
                        new
                        {
                            Id = 31,
                            Difficulty = 2,
                            Item1 = "fur",
                            Item2 = "rack",
                            Item3 = "tail",
                            Solution = "coat"
                        },
                        new
                        {
                            Id = 32,
                            Difficulty = 4,
                            Item1 = "stick",
                            Item2 = "maker",
                            Item3 = "point",
                            Solution = "match"
                        },
                        new
                        {
                            Id = 33,
                            Difficulty = 2,
                            Item1 = "hound",
                            Item2 = "pressure",
                            Item3 = "shot",
                            Solution = "blood"
                        },
                        new
                        {
                            Id = 34,
                            Difficulty = 3,
                            Item1 = "fox",
                            Item2 = "man",
                            Item3 = "peep",
                            Solution = "hole"
                        },
                        new
                        {
                            Id = 35,
                            Difficulty = 1,
                            Item1 = "sleeping",
                            Item2 = "bean",
                            Item3 = "trash",
                            Solution = "bag"
                        },
                        new
                        {
                            Id = 36,
                            Difficulty = 4,
                            Item1 = "dust",
                            Item2 = "cereal",
                            Item3 = "fish",
                            Solution = "bowl"
                        },
                        new
                        {
                            Id = 37,
                            Difficulty = 3,
                            Item1 = "light",
                            Item2 = "birthday",
                            Item3 = "stick",
                            Solution = "candle"
                        },
                        new
                        {
                            Id = 38,
                            Difficulty = 1,
                            Item1 = "food",
                            Item2 = "forward",
                            Item3 = "break",
                            Solution = "fast"
                        },
                        new
                        {
                            Id = 39,
                            Difficulty = 3,
                            Item1 = "shine",
                            Item2 = "beam",
                            Item3 = "struck",
                            Solution = "moon"
                        },
                        new
                        {
                            Id = 40,
                            Difficulty = 3,
                            Item1 = "peach",
                            Item2 = "arm",
                            Item3 = "tar",
                            Solution = "pit"
                        },
                        new
                        {
                            Id = 41,
                            Difficulty = 1,
                            Item1 = "water",
                            Item2 = "mine",
                            Item3 = "shaker",
                            Solution = "salt"
                        },
                        new
                        {
                            Id = 42,
                            Difficulty = 3,
                            Item1 = "palm",
                            Item2 = "shoe",
                            Item3 = "house",
                            Solution = "tree"
                        },
                        new
                        {
                            Id = 43,
                            Difficulty = 2,
                            Item1 = "basket",
                            Item2 = "eight",
                            Item3 = "snow",
                            Solution = "ball"
                        },
                        new
                        {
                            Id = 44,
                            Difficulty = 3,
                            Item1 = "wheel",
                            Item2 = "hand",
                            Item3 = "shopping",
                            Solution = "cart"
                        },
                        new
                        {
                            Id = 45,
                            Difficulty = 4,
                            Item1 = "right",
                            Item2 = "cat",
                            Item3 = "carbon",
                            Solution = "copy"
                        },
                        new
                        {
                            Id = 46,
                            Difficulty = 5,
                            Item1 = "home",
                            Item2 = "sea",
                            Item3 = "bed",
                            Solution = "sick"
                        },
                        new
                        {
                            Id = 47,
                            Difficulty = 1,
                            Item1 = "nuclear",
                            Item2 = "feud",
                            Item3 = "album",
                            Solution = "family"
                        },
                        new
                        {
                            Id = 48,
                            Difficulty = 1,
                            Item1 = "sandwich",
                            Item2 = "house",
                            Item3 = "golf",
                            Solution = "club"
                        },
                        new
                        {
                            Id = 49,
                            Difficulty = 4,
                            Item1 = "cross",
                            Item2 = "rain",
                            Item3 = "tie",
                            Solution = "bow"
                        },
                        new
                        {
                            Id = 50,
                            Difficulty = 3,
                            Item1 = "sage",
                            Item2 = "paint",
                            Item3 = "hair",
                            Solution = "brush"
                        },
                        new
                        {
                            Id = 51,
                            Difficulty = 3,
                            Item1 = "french",
                            Item2 = "car",
                            Item3 = "shoe",
                            Solution = "horn"
                        },
                        new
                        {
                            Id = 52,
                            Difficulty = 3,
                            Item1 = "boot",
                            Item2 = "summer",
                            Item3 = "ground",
                            Solution = "camp"
                        },
                        new
                        {
                            Id = 53,
                            Difficulty = 4,
                            Item1 = "chamber",
                            Item2 = "mask",
                            Item3 = "natural",
                            Solution = "gas"
                        },
                        new
                        {
                            Id = 54,
                            Difficulty = 3,
                            Item1 = "mill",
                            Item2 = "tooth",
                            Item3 = "dust",
                            Solution = "saw"
                        },
                        new
                        {
                            Id = 55,
                            Difficulty = 3,
                            Item1 = "main",
                            Item2 = "sweeper",
                            Item3 = "light",
                            Solution = "street"
                        },
                        new
                        {
                            Id = 56,
                            Difficulty = 3,
                            Item1 = "pike",
                            Item2 = "coat",
                            Item3 = "signal",
                            Solution = "turn"
                        },
                        new
                        {
                            Id = 57,
                            Difficulty = 4,
                            Item1 = "office",
                            Item2 = "mail",
                            Item3 = "hat",
                            Solution = "box"
                        },
                        new
                        {
                            Id = 58,
                            Difficulty = 3,
                            Item1 = "fly",
                            Item2 = "clip",
                            Item3 = "wall",
                            Solution = "paper"
                        },
                        new
                        {
                            Id = 59,
                            Difficulty = 4,
                            Item1 = "age",
                            Item2 = "mile",
                            Item3 = "sand",
                            Solution = "stone"
                        },
                        new
                        {
                            Id = 60,
                            Difficulty = 4,
                            Item1 = "catcher",
                            Item2 = "food",
                            Item3 = "hot",
                            Solution = "dog"
                        },
                        new
                        {
                            Id = 61,
                            Difficulty = 3,
                            Item1 = "wagon",
                            Item2 = "break",
                            Item3 = "radio",
                            Solution = "station"
                        },
                        new
                        {
                            Id = 62,
                            Difficulty = 4,
                            Item1 = "tank",
                            Item2 = "hill",
                            Item3 = "secret",
                            Solution = "top"
                        },
                        new
                        {
                            Id = 63,
                            Difficulty = 4,
                            Item1 = "health",
                            Item2 = "taker",
                            Item3 = "less",
                            Solution = "care"
                        },
                        new
                        {
                            Id = 64,
                            Difficulty = 4,
                            Item1 = "lift",
                            Item2 = "card",
                            Item3 = "mask",
                            Solution = "face"
                        },
                        new
                        {
                            Id = 65,
                            Difficulty = 3,
                            Item1 = "dress",
                            Item2 = "dial",
                            Item3 = "flower",
                            Solution = "sun"
                        },
                        new
                        {
                            Id = 66,
                            Difficulty = 4,
                            Item1 = "force",
                            Item2 = "line",
                            Item3 = "mail",
                            Solution = "air"
                        },
                        new
                        {
                            Id = 67,
                            Difficulty = 4,
                            Item1 = "guy",
                            Item2 = "rain",
                            Item3 = "down",
                            Solution = "fall"
                        },
                        new
                        {
                            Id = 68,
                            Difficulty = 3,
                            Item1 = "eight",
                            Item2 = "skate",
                            Item3 = "stick",
                            Solution = "figure"
                        },
                        new
                        {
                            Id = 69,
                            Difficulty = 3,
                            Item1 = "down",
                            Item2 = "question",
                            Item3 = "check",
                            Solution = "mark"
                        },
                        new
                        {
                            Id = 70,
                            Difficulty = 4,
                            Item1 = "animal",
                            Item2 = "back",
                            Item3 = "rat",
                            Solution = "pack"
                        },
                        new
                        {
                            Id = 71,
                            Difficulty = 4,
                            Item1 = "officer",
                            Item2 = "cash",
                            Item3 = "larceny",
                            Solution = "petty"
                        },
                        new
                        {
                            Id = 72,
                            Difficulty = 4,
                            Item1 = "pine",
                            Item2 = "crab",
                            Item3 = "sauce",
                            Solution = "apple"
                        },
                        new
                        {
                            Id = 73,
                            Difficulty = 4,
                            Item1 = "house",
                            Item2 = "thumb",
                            Item3 = "pepper",
                            Solution = "green"
                        },
                        new
                        {
                            Id = 74,
                            Difficulty = 3,
                            Item1 = "carpet",
                            Item2 = "alert",
                            Item3 = "ink",
                            Solution = "red"
                        },
                        new
                        {
                            Id = 75,
                            Difficulty = 3,
                            Item1 = "master",
                            Item2 = "toss",
                            Item3 = "finger",
                            Solution = "ring"
                        },
                        new
                        {
                            Id = 76,
                            Difficulty = 3,
                            Item1 = "hammer",
                            Item2 = "gear",
                            Item3 = "hunter",
                            Solution = "head"
                        },
                        new
                        {
                            Id = 77,
                            Difficulty = 3,
                            Item1 = "knife",
                            Item2 = "light",
                            Item3 = "pal",
                            Solution = "pen"
                        },
                        new
                        {
                            Id = 78,
                            Difficulty = 4,
                            Item1 = "foul",
                            Item2 = "ground",
                            Item3 = "mate",
                            Solution = "play"
                        },
                        new
                        {
                            Id = 79,
                            Difficulty = 4,
                            Item1 = "change",
                            Item2 = "circuit",
                            Item3 = "cake",
                            Solution = "short"
                        },
                        new
                        {
                            Id = 80,
                            Difficulty = 3,
                            Item1 = "way",
                            Item2 = "board",
                            Item3 = "sleep",
                            Solution = "walk"
                        },
                        new
                        {
                            Id = 81,
                            Difficulty = 3,
                            Item1 = "blank",
                            Item2 = "list",
                            Item3 = "mate",
                            Solution = "check"
                        },
                        new
                        {
                            Id = 82,
                            Difficulty = 4,
                            Item1 = "tail",
                            Item2 = "water",
                            Item3 = "flood",
                            Solution = "gate"
                        },
                        new
                        {
                            Id = 83,
                            Difficulty = 4,
                            Item1 = "marshal",
                            Item2 = "child",
                            Item3 = "piano",
                            Solution = "grand"
                        },
                        new
                        {
                            Id = 84,
                            Difficulty = 4,
                            Item1 = "cover",
                            Item2 = "arm",
                            Item3 = "wear",
                            Solution = "under"
                        },
                        new
                        {
                            Id = 85,
                            Difficulty = 4,
                            Item1 = "rain",
                            Item2 = "test",
                            Item3 = "stomach",
                            Solution = "acid"
                        },
                        new
                        {
                            Id = 86,
                            Difficulty = 4,
                            Item1 = "time",
                            Item2 = "blown",
                            Item3 = "nelson",
                            Solution = "full"
                        },
                        new
                        {
                            Id = 87,
                            Difficulty = 4,
                            Item1 = "pile",
                            Item2 = "market",
                            Item3 = "room",
                            Solution = "stock"
                        },
                        new
                        {
                            Id = 88,
                            Difficulty = 2,
                            Item1 = "mouse",
                            Item2 = "bear",
                            Item3 = "sand",
                            Solution = "trap"
                        },
                        new
                        {
                            Id = 89,
                            Difficulty = 3,
                            Item1 = "cat",
                            Item2 = "number",
                            Item3 = "phone",
                            Solution = "call"
                        },
                        new
                        {
                            Id = 90,
                            Difficulty = 3,
                            Item1 = "keg",
                            Item2 = "puff",
                            Item3 = "room",
                            Solution = "powder"
                        },
                        new
                        {
                            Id = 91,
                            Difficulty = 5,
                            Item1 = "trip",
                            Item2 = "house",
                            Item3 = "goal",
                            Solution = "field"
                        },
                        new
                        {
                            Id = 92,
                            Difficulty = 5,
                            Item1 = "fork",
                            Item2 = "dark",
                            Item3 = "man",
                            Solution = "pitch"
                        },
                        new
                        {
                            Id = 93,
                            Difficulty = 5,
                            Item1 = "fence",
                            Item2 = "card",
                            Item3 = "master",
                            Solution = "post"
                        },
                        new
                        {
                            Id = 94,
                            Difficulty = 4,
                            Item1 = "test",
                            Item2 = "runner",
                            Item3 = "map",
                            Solution = "road"
                        },
                        new
                        {
                            Id = 95,
                            Difficulty = 4,
                            Item1 = "dive",
                            Item2 = "light",
                            Item3 = "rocket",
                            Solution = "sky"
                        },
                        new
                        {
                            Id = 96,
                            Difficulty = 4,
                            Item1 = "man",
                            Item2 = "glue",
                            Item3 = "star",
                            Solution = "super"
                        },
                        new
                        {
                            Id = 97,
                            Difficulty = 4,
                            Item1 = "tooth",
                            Item2 = "potato",
                            Item3 = "heart",
                            Solution = "sweet"
                        },
                        new
                        {
                            Id = 98,
                            Difficulty = 5,
                            Item1 = "illness",
                            Item2 = "bus",
                            Item3 = "computer",
                            Solution = "terminal"
                        },
                        new
                        {
                            Id = 99,
                            Difficulty = 3,
                            Item1 = "type",
                            Item2 = "ghost",
                            Item3 = "screen",
                            Solution = "writer"
                        },
                        new
                        {
                            Id = 100,
                            Difficulty = 5,
                            Item1 = "mail",
                            Item2 = "board",
                            Item3 = "lung",
                            Solution = "black"
                        },
                        new
                        {
                            Id = 101,
                            Difficulty = 4,
                            Item1 = "teeth",
                            Item2 = "arrest",
                            Item3 = "start",
                            Solution = "false"
                        },
                        new
                        {
                            Id = 102,
                            Difficulty = 4,
                            Item1 = "iron",
                            Item2 = "shovel",
                            Item3 = "engine",
                            Solution = "steam"
                        },
                        new
                        {
                            Id = 103,
                            Difficulty = 3,
                            Item1 = "wet",
                            Item2 = "law",
                            Item3 = "business",
                            Solution = "suit"
                        },
                        new
                        {
                            Id = 104,
                            Difficulty = 4,
                            Item1 = "rope",
                            Item2 = "truck",
                            Item3 = "line",
                            Solution = "tow"
                        },
                        new
                        {
                            Id = 105,
                            Difficulty = 4,
                            Item1 = "off",
                            Item2 = "military",
                            Item3 = "first",
                            Solution = "base"
                        },
                        new
                        {
                            Id = 106,
                            Difficulty = 4,
                            Item1 = "spoon",
                            Item2 = "cloth",
                            Item3 = "card",
                            Solution = "table"
                        },
                        new
                        {
                            Id = 107,
                            Difficulty = 4,
                            Item1 = "cut",
                            Item2 = "cream",
                            Item3 = "war",
                            Solution = "cold"
                        },
                        new
                        {
                            Id = 108,
                            Difficulty = 4,
                            Item1 = "note",
                            Item2 = "chain",
                            Item3 = "master",
                            Solution = "key"
                        },
                        new
                        {
                            Id = 109,
                            Difficulty = 4,
                            Item1 = "shock",
                            Item2 = "shave",
                            Item3 = "taste",
                            Solution = "after"
                        },
                        new
                        {
                            Id = 110,
                            Difficulty = 5,
                            Item1 = "wise",
                            Item2 = "work",
                            Item3 = "tower",
                            Solution = "clock"
                        },
                        new
                        {
                            Id = 111,
                            Difficulty = 4,
                            Item1 = "grass",
                            Item2 = "king",
                            Item3 = "meat",
                            Solution = "crab"
                        },
                        new
                        {
                            Id = 112,
                            Difficulty = 4,
                            Item1 = "baby",
                            Item2 = "spring",
                            Item3 = "cap",
                            Solution = "shower"
                        },
                        new
                        {
                            Id = 113,
                            Difficulty = 4,
                            Item1 = "break",
                            Item2 = "bean",
                            Item3 = "cake",
                            Solution = "coffee"
                        },
                        new
                        {
                            Id = 114,
                            Difficulty = 5,
                            Item1 = "cry",
                            Item2 = "front",
                            Item3 = "ship",
                            Solution = "battle"
                        },
                        new
                        {
                            Id = 115,
                            Difficulty = 4,
                            Item1 = "hold",
                            Item2 = "print",
                            Item3 = "stool",
                            Solution = "foot"
                        },
                        new
                        {
                            Id = 116,
                            Difficulty = 4,
                            Item1 = "roll",
                            Item2 = "bean",
                            Item3 = "fish",
                            Solution = "jelly"
                        },
                        new
                        {
                            Id = 117,
                            Difficulty = 3,
                            Item1 = "horse",
                            Item2 = "human",
                            Item3 = "drag",
                            Solution = "race"
                        },
                        new
                        {
                            Id = 118,
                            Difficulty = 4,
                            Item1 = "oil",
                            Item2 = "bar",
                            Item3 = "tuna",
                            Solution = "salad"
                        },
                        new
                        {
                            Id = 119,
                            Difficulty = 4,
                            Item1 = "bottom",
                            Item2 = "curve",
                            Item3 = "hop",
                            Solution = "bell"
                        },
                        new
                        {
                            Id = 120,
                            Difficulty = 4,
                            Item1 = "tomato",
                            Item2 = "bomb",
                            Item3 = "picker",
                            Solution = "cherry"
                        },
                        new
                        {
                            Id = 121,
                            Difficulty = 4,
                            Item1 = "pea",
                            Item2 = "shell",
                            Item3 = "chest",
                            Solution = "nut"
                        },
                        new
                        {
                            Id = 122,
                            Difficulty = 5,
                            Item1 = "line",
                            Item2 = "fruit",
                            Item3 = "drunk",
                            Solution = "punch"
                        },
                        new
                        {
                            Id = 123,
                            Difficulty = 5,
                            Item1 = "bump",
                            Item2 = "egg",
                            Item3 = "step",
                            Solution = "goose"
                        },
                        new
                        {
                            Id = 124,
                            Difficulty = 4,
                            Item1 = "fight",
                            Item2 = "control",
                            Item3 = "machine",
                            Solution = "gun"
                        },
                        new
                        {
                            Id = 125,
                            Difficulty = 4,
                            Item1 = "home",
                            Item2 = "arm",
                            Item3 = "room",
                            Solution = "rest"
                        },
                        new
                        {
                            Id = 126,
                            Difficulty = 5,
                            Item1 = "child",
                            Item2 = "scan",
                            Item3 = "wash",
                            Solution = "brain"
                        },
                        new
                        {
                            Id = 127,
                            Difficulty = 4,
                            Item1 = "nose",
                            Item2 = "stone",
                            Item3 = "bear",
                            Solution = "brown"
                        },
                        new
                        {
                            Id = 128,
                            Difficulty = 5,
                            Item1 = "end",
                            Item2 = "line",
                            Item3 = "lock",
                            Solution = "dead"
                        },
                        new
                        {
                            Id = 129,
                            Difficulty = 5,
                            Item1 = "control",
                            Item2 = "place",
                            Item3 = "rate",
                            Solution = "birth"
                        },
                        new
                        {
                            Id = 130,
                            Difficulty = 5,
                            Item1 = "lounge",
                            Item2 = "hour",
                            Item3 = "napkin",
                            Solution = "cocktail"
                        },
                        new
                        {
                            Id = 131,
                            Difficulty = 5,
                            Item1 = "artist",
                            Item2 = "hatch",
                            Item3 = "route",
                            Solution = "escape"
                        },
                        new
                        {
                            Id = 132,
                            Difficulty = 5,
                            Item1 = "pet",
                            Item2 = "bottom",
                            Item3 = "garden",
                            Solution = "rock"
                        },
                        new
                        {
                            Id = 133,
                            Difficulty = 5,
                            Item1 = "mate",
                            Item2 = "shoes",
                            Item3 = "total",
                            Solution = "running"
                        },
                        new
                        {
                            Id = 134,
                            Difficulty = 5,
                            Item1 = "self",
                            Item2 = "attorney",
                            Item3 = "spending",
                            Solution = "defense"
                        },
                        new
                        {
                            Id = 135,
                            Difficulty = 4,
                            Item1 = "board",
                            Item2 = "blade",
                            Item3 = "back",
                            Solution = "switch"
                        },
                        new
                        {
                            Id = 136,
                            Difficulty = 5,
                            Item1 = "land",
                            Item2 = "hand",
                            Item3 = "house",
                            Solution = "farm"
                        },
                        new
                        {
                            Id = 137,
                            Difficulty = 5,
                            Item1 = "hungry",
                            Item2 = "order",
                            Item3 = "belt",
                            Solution = "money"
                        },
                        new
                        {
                            Id = 138,
                            Difficulty = 5,
                            Item1 = "forward",
                            Item2 = "flush",
                            Item3 = "razor",
                            Solution = "straight"
                        },
                        new
                        {
                            Id = 139,
                            Difficulty = 5,
                            Item1 = "shadow",
                            Item2 = "chart",
                            Item3 = "drop",
                            Solution = "eye"
                        },
                        new
                        {
                            Id = 140,
                            Difficulty = 5,
                            Item1 = "way",
                            Item2 = "ground",
                            Item3 = "weather",
                            Solution = "fair"
                        },
                        new
                        {
                            Id = 141,
                            Difficulty = 5,
                            Item1 = "cast",
                            Item2 = "side",
                            Item3 = "jump",
                            Solution = "broad"
                        },
                        new
                        {
                            Id = 142,
                            Difficulty = 4,
                            Item1 = "back",
                            Item2 = "step",
                            Item3 = "screen",
                            Solution = "door"
                        },
                        new
                        {
                            Id = 143,
                            Difficulty = 5,
                            Item1 = "reading",
                            Item2 = "service",
                            Item3 = "stick",
                            Solution = "lip"
                        },
                        new
                        {
                            Id = 144,
                            Difficulty = 5,
                            Item1 = "over",
                            Item2 = "plant",
                            Item3 = "horse",
                            Solution = "power"
                        },
                        new
                        {
                            Id = 145,
                            Difficulty = 1,
                            Item1 = "falling",
                            Item2 = "actor",
                            Item3 = "dust",
                            Solution = "star"
                        },
                        new
                        {
                            Id = 146,
                            Difficulty = 1,
                            Item1 = "broken",
                            Item2 = "clear",
                            Item3 = "eye",
                            Solution = "glass"
                        },
                        new
                        {
                            Id = 147,
                            Difficulty = 1,
                            Item1 = "skunk",
                            Item2 = "kings",
                            Item3 = "boiled",
                            Solution = "cabbage"
                        },
                        new
                        {
                            Id = 148,
                            Difficulty = 2,
                            Item1 = "widow",
                            Item2 = "bite",
                            Item3 = "monkey",
                            Solution = "spider"
                        },
                        new
                        {
                            Id = 149,
                            Difficulty = 2,
                            Item1 = "bass",
                            Item2 = "complex",
                            Item3 = "sleep",
                            Solution = "deep"
                        },
                        new
                        {
                            Id = 150,
                            Difficulty = 2,
                            Item1 = "coin",
                            Item2 = "quick",
                            Item3 = "spoon",
                            Solution = "silver"
                        },
                        new
                        {
                            Id = 151,
                            Difficulty = 2,
                            Item1 = "gold",
                            Item2 = "stool",
                            Item3 = "tender",
                            Solution = "bar"
                        },
                        new
                        {
                            Id = 152,
                            Difficulty = 2,
                            Item1 = "time",
                            Item2 = "hair",
                            Item3 = "stretch",
                            Solution = "long"
                        },
                        new
                        {
                            Id = 153,
                            Difficulty = 3,
                            Item1 = "cracker",
                            Item2 = "union",
                            Item3 = "rabbit",
                            Solution = "jack"
                        },
                        new
                        {
                            Id = 154,
                            Difficulty = 3,
                            Item1 = "bald",
                            Item2 = "screech",
                            Item3 = "emblem",
                            Solution = "eagle"
                        },
                        new
                        {
                            Id = 155,
                            Difficulty = 3,
                            Item1 = "blood",
                            Item2 = "music",
                            Item3 = "cheese",
                            Solution = "blue"
                        },
                        new
                        {
                            Id = 156,
                            Difficulty = 3,
                            Item1 = "manners",
                            Item2 = "round",
                            Item3 = "tennis",
                            Solution = "table"
                        },
                        new
                        {
                            Id = 157,
                            Difficulty = 3,
                            Item1 = "off",
                            Item2 = "trumpet",
                            Item3 = "atomic",
                            Solution = "blast"
                        },
                        new
                        {
                            Id = 158,
                            Difficulty = 3,
                            Item1 = "playing",
                            Item2 = "credit",
                            Item3 = "report",
                            Solution = "card"
                        },
                        new
                        {
                            Id = 159,
                            Difficulty = 3,
                            Item1 = "rabbit",
                            Item2 = "cloud",
                            Item3 = "house",
                            Solution = "white"
                        },
                        new
                        {
                            Id = 160,
                            Difficulty = 3,
                            Item1 = "room",
                            Item2 = "blood",
                            Item3 = "salts",
                            Solution = "bath"
                        },
                        new
                        {
                            Id = 161,
                            Difficulty = 3,
                            Item1 = "salt",
                            Item2 = "deep",
                            Item3 = "foam",
                            Solution = "sea"
                        },
                        new
                        {
                            Id = 162,
                            Difficulty = 3,
                            Item1 = "square",
                            Item2 = "cardboard",
                            Item3 = "open",
                            Solution = "box"
                        },
                        new
                        {
                            Id = 163,
                            Difficulty = 3,
                            Item1 = "water",
                            Item2 = "tobacco",
                            Item3 = "stove",
                            Solution = "pipe"
                        },
                        new
                        {
                            Id = 164,
                            Difficulty = 3,
                            Item1 = "ache",
                            Item2 = "hunter",
                            Item3 = "cabbage",
                            Solution = "head"
                        },
                        new
                        {
                            Id = 165,
                            Difficulty = 3,
                            Item1 = "chamber",
                            Item2 = "staff",
                            Item3 = "box",
                            Solution = "music"
                        },
                        new
                        {
                            Id = 166,
                            Difficulty = 3,
                            Item1 = "high",
                            Item2 = "book",
                            Item3 = "sour",
                            Solution = "note"
                        },
                        new
                        {
                            Id = 167,
                            Difficulty = 3,
                            Item1 = "lick",
                            Item2 = "sprinkle",
                            Item3 = "mines",
                            Solution = "salt"
                        },
                        new
                        {
                            Id = 168,
                            Difficulty = 3,
                            Item1 = "pure",
                            Item2 = "blue",
                            Item3 = "fall",
                            Solution = "water"
                        },
                        new
                        {
                            Id = 169,
                            Difficulty = 3,
                            Item1 = "snack",
                            Item2 = "line",
                            Item3 = "birthday",
                            Solution = "party"
                        },
                        new
                        {
                            Id = 170,
                            Difficulty = 3,
                            Item1 = "square",
                            Item2 = "telephone",
                            Item3 = "club",
                            Solution = "book"
                        },
                        new
                        {
                            Id = 171,
                            Difficulty = 3,
                            Item1 = "surprise",
                            Item2 = "wrap",
                            Item3 = "care",
                            Solution = "gift"
                        },
                        new
                        {
                            Id = 172,
                            Difficulty = 3,
                            Item1 = "ticket",
                            Item2 = "shop",
                            Item3 = "broker",
                            Solution = "pawn"
                        },
                        new
                        {
                            Id = 173,
                            Difficulty = 3,
                            Item1 = "barrel",
                            Item2 = "root",
                            Item3 = "belly",
                            Solution = "beer"
                        },
                        new
                        {
                            Id = 174,
                            Difficulty = 3,
                            Item1 = "blade",
                            Item2 = "witted",
                            Item3 = "weary",
                            Solution = "dull"
                        },
                        new
                        {
                            Id = 175,
                            Difficulty = 3,
                            Item1 = "cherry",
                            Item2 = "time",
                            Item3 = "smell",
                            Solution = "blossom"
                        },
                        new
                        {
                            Id = 176,
                            Difficulty = 3,
                            Item1 = "notch",
                            Item2 = "flight",
                            Item3 = "spin",
                            Solution = "top"
                        },
                        new
                        {
                            Id = 177,
                            Difficulty = 3,
                            Item1 = "strap",
                            Item2 = "pocket",
                            Item3 = "time",
                            Solution = "watch"
                        },
                        new
                        {
                            Id = 178,
                            Difficulty = 3,
                            Item1 = "walker",
                            Item2 = "main",
                            Item3 = "sweeper",
                            Solution = "street"
                        },
                        new
                        {
                            Id = 179,
                            Difficulty = 3,
                            Item1 = "wicked",
                            Item2 = "bustle",
                            Item3 = "slicker",
                            Solution = "city"
                        },
                        new
                        {
                            Id = 180,
                            Difficulty = 4,
                            Item1 = "chocolate",
                            Item2 = "fortune",
                            Item3 = "tin",
                            Solution = "cookie"
                        },
                        new
                        {
                            Id = 181,
                            Difficulty = 4,
                            Item1 = "color",
                            Item2 = "numbers",
                            Item3 = "oil",
                            Solution = "paint"
                        },
                        new
                        {
                            Id = 182,
                            Difficulty = 4,
                            Item1 = "mouse",
                            Item2 = "sharp",
                            Item3 = "blue",
                            Solution = "cheese"
                        },
                        new
                        {
                            Id = 183,
                            Difficulty = 4,
                            Item1 = "sandwich",
                            Item2 = "golf",
                            Item3 = "foot",
                            Solution = "club"
                        },
                        new
                        {
                            Id = 184,
                            Difficulty = 4,
                            Item1 = "silk",
                            Item2 = "cream",
                            Item3 = "even",
                            Solution = "smooth"
                        },
                        new
                        {
                            Id = 185,
                            Difficulty = 4,
                            Item1 = "speak",
                            Item2 = "money",
                            Item3 = "street",
                            Solution = "easy"
                        },
                        new
                        {
                            Id = 186,
                            Difficulty = 4,
                            Item1 = "big",
                            Item2 = "leaf",
                            Item3 = "shade",
                            Solution = "tree"
                        },
                        new
                        {
                            Id = 187,
                            Difficulty = 4,
                            Item1 = "envy",
                            Item2 = "golf",
                            Item3 = "beans",
                            Solution = "green"
                        },
                        new
                        {
                            Id = 188,
                            Difficulty = 4,
                            Item1 = "hall",
                            Item2 = "car",
                            Item3 = "swimming",
                            Solution = "pool"
                        },
                        new
                        {
                            Id = 189,
                            Difficulty = 4,
                            Item1 = "ink",
                            Item2 = "herring",
                            Item3 = "neck",
                            Solution = "red"
                        },
                        new
                        {
                            Id = 190,
                            Difficulty = 4,
                            Item1 = "measure",
                            Item2 = "desk",
                            Item3 = "scotch",
                            Solution = "tape"
                        },
                        new
                        {
                            Id = 191,
                            Difficulty = 4,
                            Item1 = "strike",
                            Item2 = "same",
                            Item3 = "tennis",
                            Solution = "match"
                        },
                        new
                        {
                            Id = 192,
                            Difficulty = 4,
                            Item1 = "athletes",
                            Item2 = "web",
                            Item3 = "rabbit",
                            Solution = "foot"
                        },
                        new
                        {
                            Id = 193,
                            Difficulty = 4,
                            Item1 = "board",
                            Item2 = "magic",
                            Item3 = "death",
                            Solution = "black"
                        },
                        new
                        {
                            Id = 194,
                            Difficulty = 4,
                            Item1 = "lapse",
                            Item2 = "vivid",
                            Item3 = "elephant",
                            Solution = "memory"
                        },
                        new
                        {
                            Id = 195,
                            Difficulty = 4,
                            Item1 = "puss",
                            Item2 = "tart",
                            Item3 = "spoiled",
                            Solution = "sour"
                        },
                        new
                        {
                            Id = 196,
                            Difficulty = 4,
                            Item1 = "rock",
                            Item2 = "times",
                            Item3 = "steel",
                            Solution = "hard"
                        },
                        new
                        {
                            Id = 197,
                            Difficulty = 4,
                            Item1 = "stop",
                            Item2 = "petty",
                            Item3 = "sneak",
                            Solution = "thief"
                        },
                        new
                        {
                            Id = 198,
                            Difficulty = 4,
                            Item1 = "thread",
                            Item2 = "pine",
                            Item3 = "pain",
                            Solution = "needle"
                        },
                        new
                        {
                            Id = 199,
                            Difficulty = 4,
                            Item1 = "zone",
                            Item2 = "still",
                            Item3 = "noise",
                            Solution = "quiet"
                        },
                        new
                        {
                            Id = 200,
                            Difficulty = 4,
                            Item1 = "cloth",
                            Item2 = "sad",
                            Item3 = "out",
                            Solution = "sack"
                        },
                        new
                        {
                            Id = 201,
                            Difficulty = 4,
                            Item1 = "cotton",
                            Item2 = "bathtub",
                            Item3 = "tonic",
                            Solution = "gin"
                        },
                        new
                        {
                            Id = 202,
                            Difficulty = 4,
                            Item1 = "foot",
                            Item2 = "collection",
                            Item3 = "out",
                            Solution = "stamp"
                        },
                        new
                        {
                            Id = 203,
                            Difficulty = 4,
                            Item1 = "inch",
                            Item2 = "deal",
                            Item3 = "peg",
                            Solution = "square"
                        },
                        new
                        {
                            Id = 204,
                            Difficulty = 4,
                            Item1 = "jump",
                            Item2 = "kill",
                            Item3 = "bliss",
                            Solution = "joy"
                        },
                        new
                        {
                            Id = 205,
                            Difficulty = 4,
                            Item1 = "magic",
                            Item2 = "plush",
                            Item3 = "floor",
                            Solution = "carpet"
                        },
                        new
                        {
                            Id = 206,
                            Difficulty = 4,
                            Item1 = "note",
                            Item2 = "dive",
                            Item3 = "chair",
                            Solution = "high"
                        },
                        new
                        {
                            Id = 207,
                            Difficulty = 4,
                            Item1 = "stalk",
                            Item2 = "trainer",
                            Item3 = "king",
                            Solution = "lion"
                        },
                        new
                        {
                            Id = 208,
                            Difficulty = 4,
                            Item1 = "bump",
                            Item2 = "throat",
                            Item3 = "sum",
                            Solution = "lump"
                        },
                        new
                        {
                            Id = 209,
                            Difficulty = 4,
                            Item1 = "shopping",
                            Item2 = "washer",
                            Item3 = "picture",
                            Solution = "window"
                        },
                        new
                        {
                            Id = 210,
                            Difficulty = 4,
                            Item1 = "blank",
                            Item2 = "white",
                            Item3 = "lines",
                            Solution = "paper"
                        },
                        new
                        {
                            Id = 211,
                            Difficulty = 4,
                            Item1 = "stick",
                            Item2 = "light",
                            Item3 = "birthday",
                            Solution = "candle"
                        },
                        new
                        {
                            Id = 212,
                            Difficulty = 5,
                            Item1 = "sore",
                            Item2 = "shoulder",
                            Item3 = "sweat",
                            Solution = "cold"
                        },
                        new
                        {
                            Id = 213,
                            Difficulty = 4,
                            Item1 = "house",
                            Item2 = "blanket",
                            Item3 = "ball",
                            Solution = "beach"
                        },
                        new
                        {
                            Id = 214,
                            Difficulty = 1,
                            Item1 = "trap",
                            Item2 = "polar",
                            Item3 = "claw",
                            Solution = "bear"
                        },
                        new
                        {
                            Id = 215,
                            Difficulty = 1,
                            Item1 = "cinder",
                            Item2 = "building",
                            Item3 = "buster",
                            Solution = "block"
                        },
                        new
                        {
                            Id = 216,
                            Difficulty = 4,
                            Item1 = "line",
                            Item2 = "patrol",
                            Item3 = "town",
                            Solution = "border"
                        },
                        new
                        {
                            Id = 217,
                            Difficulty = 1,
                            Item1 = "thorn",
                            Item2 = "whack",
                            Item3 = "rose",
                            Solution = "bush"
                        },
                        new
                        {
                            Id = 218,
                            Difficulty = 2,
                            Item1 = "garbage",
                            Item2 = "beer",
                            Item3 = "paint",
                            Solution = "can"
                        },
                        new
                        {
                            Id = 219,
                            Difficulty = 1,
                            Item1 = "scan",
                            Item2 = "nap",
                            Item3 = "burglar",
                            Solution = "cat"
                        },
                        new
                        {
                            Id = 220,
                            Difficulty = 2,
                            Item1 = "trap",
                            Item2 = "back",
                            Item3 = "screen",
                            Solution = "door"
                        },
                        new
                        {
                            Id = 221,
                            Difficulty = 4,
                            Item1 = "through",
                            Item2 = "disk",
                            Item3 = "way",
                            Solution = "drive"
                        },
                        new
                        {
                            Id = 222,
                            Difficulty = 4,
                            Item1 = "tax",
                            Item2 = "real",
                            Item3 = "fourth",
                            Solution = "estate"
                        },
                        new
                        {
                            Id = 223,
                            Difficulty = 4,
                            Item1 = "life",
                            Item2 = "color",
                            Item3 = "coast",
                            Solution = "guard"
                        },
                        new
                        {
                            Id = 224,
                            Difficulty = 4,
                            Item1 = "wave",
                            Item2 = "lamp",
                            Item3 = "dry",
                            Solution = "heat"
                        },
                        new
                        {
                            Id = 225,
                            Difficulty = 2,
                            Item1 = "glass",
                            Item2 = "rush",
                            Item3 = "happy",
                            Solution = "hour"
                        },
                        new
                        {
                            Id = 226,
                            Difficulty = 3,
                            Item1 = "waffle",
                            Item2 = "lung",
                            Item3 = "tire",
                            Solution = "iron"
                        },
                        new
                        {
                            Id = 227,
                            Difficulty = 3,
                            Item1 = "poison",
                            Item2 = "league",
                            Item3 = "creeping",
                            Solution = "ivy"
                        },
                        new
                        {
                            Id = 228,
                            Difficulty = 1,
                            Item1 = "pain",
                            Item2 = "serial",
                            Item3 = "whale",
                            Solution = "killer"
                        },
                        new
                        {
                            Id = 229,
                            Difficulty = 2,
                            Item1 = "floor",
                            Item2 = "shade",
                            Item3 = "heat",
                            Solution = "lamp"
                        },
                        new
                        {
                            Id = 230,
                            Difficulty = 2,
                            Item1 = "puppy",
                            Item2 = "TRUE",
                            Item3 = "letter",
                            Solution = "love"
                        },
                        new
                        {
                            Id = 231,
                            Difficulty = 4,
                            Item1 = "bedroom",
                            Item2 = "plan",
                            Item3 = "brew",
                            Solution = "master"
                        },
                        new
                        {
                            Id = 232,
                            Difficulty = 4,
                            Item1 = "mouth",
                            Item2 = "bike",
                            Item3 = "oil",
                            Solution = "motor"
                        },
                        new
                        {
                            Id = 233,
                            Difficulty = 2,
                            Item1 = "polish",
                            Item2 = "finger",
                            Item3 = "down",
                            Solution = "nail"
                        },
                        new
                        {
                            Id = 234,
                            Difficulty = 4,
                            Item1 = "sake",
                            Item2 = "pet",
                            Item3 = "nick",
                            Solution = "name"
                        },
                        new
                        {
                            Id = 235,
                            Difficulty = 5,
                            Item1 = "computer",
                            Item2 = "cable",
                            Item3 = "broadcast",
                            Solution = "network"
                        },
                        new
                        {
                            Id = 236,
                            Difficulty = 3,
                            Item1 = "skirts",
                            Item2 = "take",
                            Item3 = "put",
                            Solution = "out"
                        },
                        new
                        {
                            Id = 237,
                            Difficulty = 5,
                            Item1 = "jury",
                            Item2 = "door",
                            Item3 = "side",
                            Solution = "panel"
                        },
                        new
                        {
                            Id = 238,
                            Difficulty = 4,
                            Item1 = "due",
                            Item2 = "life",
                            Item3 = "tense",
                            Solution = "past"
                        },
                        new
                        {
                            Id = 239,
                            Difficulty = 4,
                            Item1 = "tomato",
                            Item2 = "cement",
                            Item3 = "tooth",
                            Solution = "paste"
                        },
                        new
                        {
                            Id = 240,
                            Difficulty = 1,
                            Item1 = "flag",
                            Item2 = "vault",
                            Item3 = "fishing",
                            Solution = "pole"
                        },
                        new
                        {
                            Id = 241,
                            Difficulty = 4,
                            Item1 = "release",
                            Item2 = "french",
                            Item3 = "secretary",
                            Solution = "press"
                        },
                        new
                        {
                            Id = 242,
                            Difficulty = 1,
                            Item1 = "dollar",
                            Item2 = "stop",
                            Item3 = "language",
                            Solution = "sign"
                        },
                        new
                        {
                            Id = 243,
                            Difficulty = 3,
                            Item1 = "quick",
                            Item2 = "spoon",
                            Item3 = "screen",
                            Solution = "silver"
                        },
                        new
                        {
                            Id = 244,
                            Difficulty = 5,
                            Item1 = "grand",
                            Item2 = "door",
                            Item3 = "bang",
                            Solution = "slam"
                        },
                        new
                        {
                            Id = 245,
                            Difficulty = 5,
                            Item1 = "dash",
                            Item2 = "happy",
                            Item3 = "stick",
                            Solution = "slap"
                        },
                        new
                        {
                            Id = 246,
                            Difficulty = 3,
                            Item1 = "ruby",
                            Item2 = "glass",
                            Item3 = "bunny",
                            Solution = "slipper"
                        },
                        new
                        {
                            Id = 247,
                            Difficulty = 3,
                            Item1 = "demon",
                            Item2 = "limit",
                            Item3 = "way",
                            Solution = "speed"
                        },
                        new
                        {
                            Id = 248,
                            Difficulty = 4,
                            Item1 = "gap",
                            Item2 = "door",
                            Item3 = "sign",
                            Solution = "stop"
                        },
                        new
                        {
                            Id = 249,
                            Difficulty = 3,
                            Item1 = "food",
                            Item2 = "front",
                            Item3 = "drug",
                            Solution = "store"
                        },
                        new
                        {
                            Id = 250,
                            Difficulty = 1,
                            Item1 = "set",
                            Item2 = "program",
                            Item3 = "cable",
                            Solution = "television"
                        },
                        new
                        {
                            Id = 251,
                            Difficulty = 5,
                            Item1 = "chest",
                            Item2 = "car",
                            Item3 = "store",
                            Solution = "toy"
                        },
                        new
                        {
                            Id = 252,
                            Difficulty = 4,
                            Item1 = "property",
                            Item2 = "moral",
                            Item3 = "price",
                            Solution = "value"
                        },
                        new
                        {
                            Id = 253,
                            Difficulty = 4,
                            Item1 = "rag",
                            Item2 = "milk",
                            Item3 = "out",
                            Solution = "weed"
                        },
                        new
                        {
                            Id = 254,
                            Difficulty = 3,
                            Item1 = "noise",
                            Item2 = "collar",
                            Item3 = "wash",
                            Solution = "white"
                        },
                        new
                        {
                            Id = 255,
                            Difficulty = 3,
                            Item1 = "bay",
                            Item2 = "picture",
                            Item3 = "washer",
                            Solution = "window"
                        },
                        new
                        {
                            Id = 256,
                            Difficulty = 2,
                            Item1 = "hard",
                            Item2 = "drift",
                            Item3 = "cutter",
                            Solution = "wood"
                        },
                        new
                        {
                            Id = 257,
                            Difficulty = 1,
                            Item1 = "cottage",
                            Item2 = "brick",
                            Item3 = "cake",
                            Solution = "cheese"
                        },
                        new
                        {
                            Id = 258,
                            Difficulty = 2,
                            Item1 = "shelf",
                            Item2 = "read",
                            Item3 = "end",
                            Solution = "book"
                        },
                        new
                        {
                            Id = 259,
                            Difficulty = 2,
                            Item1 = "sea",
                            Item2 = "home",
                            Item3 = "stomach",
                            Solution = "sick"
                        },
                        new
                        {
                            Id = 260,
                            Difficulty = 2,
                            Item1 = "car",
                            Item2 = "swimming",
                            Item3 = "cue",
                            Solution = "pool"
                        },
                        new
                        {
                            Id = 261,
                            Difficulty = 2,
                            Item1 = "cookies",
                            Item2 = "sixteen",
                            Item3 = "heart",
                            Solution = "sweet"
                        },
                        new
                        {
                            Id = 262,
                            Difficulty = 2,
                            Item1 = "lounge",
                            Item2 = "hour",
                            Item3 = "drink",
                            Solution = "cocktail"
                        },
                        new
                        {
                            Id = 263,
                            Difficulty = 2,
                            Item1 = "keel",
                            Item2 = "show",
                            Item3 = "row",
                            Solution = "boat"
                        },
                        new
                        {
                            Id = 264,
                            Difficulty = 4,
                            Item1 = "desert",
                            Item2 = "ice",
                            Item3 = "spell",
                            Solution = "dry"
                        },
                        new
                        {
                            Id = 265,
                            Difficulty = 4,
                            Item1 = "base",
                            Item2 = "show",
                            Item3 = "dance",
                            Solution = "ball"
                        },
                        new
                        {
                            Id = 266,
                            Difficulty = 4,
                            Item1 = "soap",
                            Item2 = "shoe",
                            Item3 = "tissue",
                            Solution = "box"
                        },
                        new
                        {
                            Id = 267,
                            Difficulty = 4,
                            Item1 = "hot",
                            Item2 = "butterflies",
                            Item3 = "pump",
                            Solution = "stomach"
                        },
                        new
                        {
                            Id = 268,
                            Difficulty = 2,
                            Item1 = "head",
                            Item2 = "street",
                            Item3 = "dark",
                            Solution = "light"
                        },
                        new
                        {
                            Id = 269,
                            Difficulty = 4,
                            Item1 = "room",
                            Item2 = "saturday",
                            Item3 = "salts",
                            Solution = "bath"
                        },
                        new
                        {
                            Id = 270,
                            Difficulty = 2,
                            Item1 = "surprise",
                            Item2 = "line",
                            Item3 = "birthday",
                            Solution = "party"
                        },
                        new
                        {
                            Id = 271,
                            Difficulty = 2,
                            Item1 = "red",
                            Item2 = "go",
                            Item3 = "car",
                            Solution = "stop"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
